#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"

EXCLUDE_DIRS = {".git", ".codex", ".agents", "__pycache__"}
EXCLUDE_FILES = {"FILE_STRUCTURE_GRAPH.md"}

NOTES = {
    "ARCHITECTURE.md": "High-level architecture notes for the AI-native research platform.",
    "BUILD_PLAN.md": "Implementation context and phased build plan.",
    "deliverables/export_deck_pdf.py": "Exports the PPT-sized HTML deck to PDF with Playwright.",
    "deliverables/research_ai_foundry_deck.html": "PPT-sized HTML presentation deck for the next-generation方案.",
    "deliverables/research_ai_foundry_deck.pdf": "Exported 16:9 PDF version of the presentation deck.",
    "deliverables/research_ai_foundry_plan.docx": "Formal方案书 DOCX generated from the Markdown source.",
    "deliverables/research_ai_foundry_plan.md": "Formal方案书 source Markdown.",
    "deliverables/assets/research-ai-foundry-hero.png": "Generated visual asset used in the DOCX and presentation deck.",
    "NEW_RESEARCH_AI_PLAN.md": "New Chinese方案 for an AI-native research operating system.",
    "NEXT_GEN_RESEARCH_AI_SYSTEM_IMPROVEMENTS.md": "Upgrade proposal for harness engineering, generated apps, scripts, MCP, and research capability foundry.",
    "人工智能赋能教育教学高质量发展20260320.pdf": "Reference PDF reviewed for existing Sichuan Agricultural University AI education plan.",
    "西华师范大学AI赋能教育教学进度方案.docx": "Reference docx for AI education application investigation schedule.",
    "scripts/update_file_structure_graph.py": "Regenerates this structure graph.",
}


def include(path: Path) -> bool:
    rel_parts = path.relative_to(ROOT).parts
    if any(part in EXCLUDE_DIRS for part in rel_parts):
        return False
    if path.name.startswith(".~"):
        return False
    if path.name in EXCLUDE_FILES:
        return False
    return True


def sort_key(path: Path) -> tuple[int, str]:
    return (1 if path.is_file() else 0, path.name.lower())


def render_tree(path: Path, prefix: str = "") -> list[str]:
    children = sorted([p for p in path.iterdir() if include(p)], key=sort_key)
    lines: list[str] = []
    for index, child in enumerate(children):
        connector = "`-- " if index == len(children) - 1 else "|-- "
        rel = child.relative_to(ROOT).as_posix()
        suffix = "/" if child.is_dir() else ""
        note = NOTES.get(rel)
        detail = f" - {note}" if note else ""
        lines.append(f"{prefix}{connector}{child.name}{suffix}{detail}")
        if child.is_dir():
            extension = "    " if index == len(children) - 1 else "|   "
            lines.extend(render_tree(child, prefix + extension))
    return lines


def main() -> None:
    lines = [
        "# File Structure Graph",
        "",
        "Generated by `python3 scripts/update_file_structure_graph.py`.",
        "",
        "```text",
        f"{ROOT.name}/",
        *render_tree(ROOT),
        "```",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
