#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "FILE_STRUCTURE_GRAPH.md"
IGNORED_DIRS = {".git", ".codex", ".agents", "__pycache__", "node_modules"}


def visible_entries(path: Path):
    entries = []
    for child in sorted(path.iterdir(), key=lambda item: (not item.is_dir(), item.name.lower())):
        if child.name in IGNORED_DIRS:
            continue
        entries.append(child)
    return entries


def render_tree(path: Path, prefix: str = ""):
    lines = []
    entries = visible_entries(path)
    for index, child in enumerate(entries):
        connector = "└── " if index == len(entries) - 1 else "├── "
        name = f"{child.name}/" if child.is_dir() else child.name
        lines.append(f"{prefix}{connector}{name}")
        if child.is_dir():
            extension = "    " if index == len(entries) - 1 else "│   "
            lines.extend(render_tree(child, prefix + extension))
    return lines


def main():
    lines = [
        "# File Structure Graph",
        "",
        "Generated by `scripts/update_file_structure_graph.py`.",
        "",
        "```text",
        f"{ROOT.name}/",
        *render_tree(ROOT),
        "```",
        "",
    ]
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
